services:
  - type: web
    name: telegram-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: 7790903467:AAGSnh4euRb2iItn1MsmWKRqavuqNj62i2U
      - key: CHANNEL_FROM
        value: -1002879419379
      - key: CHANNEL_TO
        value: -1002727712840
